### ISSUE TITLE
All the App Logic should be out of Dashboard Component

### ISSUE THREAD

**Issue by gabhijit** [hyphenOs/webshark-frontend#11]
Right now Dashboard component implements App logic like talking to Websocket server etc. This logic should ideally be out of the Dashboard component and the Dashboard component should only get two props - `packets` an array of packet jsons and `config` an object with three attributes - `ownConfig` , `tableConfig` and `detailsConfig` 

Right now the config object will look like - 
```javascript
{
'ownConfig' : { 'showSelectedDetails': true},
'tableConfig' : {'packetWindowSize': 50},
'detailsConfig' : {'expanded': false}
} 
```

So Overall App structure should look like 

```javascript
<App> 
  //... App UI Components, App logic (eg. talk to Websocket etc.) 
  <Dashboard packets=packets config=config/>
</App>
```

**Comment by mayurhyphenOs** [comment]
Approach:

1. Move all the websocket related code in src/App.js
2. Pass received packet(s) as `packets` props to dashboard.js
3. create src/constants/config.js with  below object
{
'ownConfig' : { 'showSelectedDetails': true},
'tableConfig' : {'packetWindowSize': 50},
'detailsConfig' : {'expanded': false}
} 
4. Import config object and pass to Dashboard as `config` props

**Comment by mayurhyphenOs** [comment]
Implementation pushed on branch 05
