### ISSUE TITLE
Configuration Options Support in UI

### ISSUE THREAD

**Issue by gabhijit** [hyphenOs/webshark-frontend#6]
As discussed in #3 There might be certain things that are configuration options - 

1. Number of Packets in a Window - Default 100 - Max 500  (Refer #3) 
2. Show detailed view of the cursor - Default True - But can be 'False' optionally. (Refer #3) 
3. Table Columns Configurable - Right now table columns are fixed - frame number, timestamp etc. It should be possible to make these columns configurable. Additional Fields to be considered for showing include - Protocol (taking values from`ip.protocol`),Source  Port / Destination Port number (taking value from `tcp.port` or `udp.port`). Right now the way it shows is wrong - we don't want it from the `frame.protocol`. 

Let's have this support for configuration, then this can be extended (eg. requested batch size later on when we support batching etc.)

**Comment by mayurhyphenOs** [comment]
Approach:
1. Use settings(icon) button to open/close settings form on click
2. Use config object from config.js as initial value for config state
3. Settings form will have component wise sections
4. Set changed settings as config state

**Comment by mayurhyphenOs** [comment]
> As discussed in #3 There might be certain things that are configuration options -
> 
> 1. Number of Packets in a Window - Default 100 - Max 500  (Refer #3)
> 2. Show detailed view of the cursor - Default True - But can be 'False' optionally. (Refer #3)
> ~~3. Table Columns Configurable - Right now table columns are fixed - frame number, timestamp etc. It should be possible to make these columns configurable. Additional Fields to be considered for showing include - Protocol (taking values from`ip.protocol`),Source  Port / Destination Port number (taking value from `tcp.port` or `udp.port`). Right now the way it shows is wrong - we don't want it from the `frame.protocol`.~~
> 
> Let's have this support for configuration, then this can be extended (eg. requested batch size later on when we support batching etc.)


- Point 1 will be done once window is implemented in #3 
- Point 2 is implemented in linked pull request #15 '
- Point 3 is deferred
